platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'IQKeyboardManager', '~> 3.2.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'JSONModel', '~> 1.1.0'
pod 'JSONKit', '~> 1.5pre'
pod 'FMDB', '~> 2.5'
pod 'LKDBHelper', '~> 2.1.3'
pod 'AIMTableViewIndexBar', '~> 0.1.1'
pod 'PinYin4Objc', '~> 1.1.1'
pod 'CYLTabBarController'
pod 'PNChart', '~> 0.8.8'